### ISSUE TITLE
R packaging all this?

### ISSUE THREAD

**Issue by antagomir** [steadyfish/JustAnotherDataBlog#1]
Hi steadyfish! just bumped into your blog post and found my way here: R API for the India Open data portal looks very  promising - if you would be interested to extend this into an R package, we would be happy to publicize it through the rOpenGov (see github/ropengov) which is a now emerging collection of R packages intended for open government data around the globe. We might also be able provide some support with the packaging if needed. Just drop a line if this sounds like something -

**Comment by steadyfish** [comment]
Hey Leo,

Thanks for your feedback! I skimmed through your collection of open
government packages on gitHub. Amazing work! I'd be happy to contribute.

A couple of things to consider though -
1. Right now there aren't vary many data-sets available through the API for
this portal, but looking at their policy documents, it seems likely that
they'll offer more datasets available in this format. The point being, this
work might not be of immediate use to larger audience at this point in time.
2. I haven't worked on any R packages before, so will need some time to get
going with this kind of work. Would appreciate your support in this regard.

Let me know what you think!

Regards,
Dhrumin S

**Comment by antagomir** [comment]
Great !

1) If the portal will be expanded then I think this would be useful; and even with the present data sets this might provide a good showcase for the admins that the API is really taken into use by the community, helping to push their effort forward as sometimes happens. Plus it is good to have the package available early on.

2) You could pick one of the ropengov packages as an example. For instance the ropengov/sotkanet package. First try convert that package as such with the script in inst/extras/build.cran.sh - once that works you can start modifying the files to replace the functions with your own. It is relatively straightforward & fast, we can also have a look and give feedback + some help if needed once you have a first draft version. We can be in touch at any point by email and github issues. Would this work?

3) If you like, you can host the package under rOpenGov account but this is not required, you can also host it elsewhere (in github), for instance under your personal account, then we just link there from the rOpenGov.

**Comment by steadyfish** [comment]
Sounds good. Will try and get this done sooner.

**Comment by steadyfish** [comment]
Hey @antagomir ,

I have r-packaged this code here - https://github.com/steadyfish/ogdindiar.

Would appreciate your feedback.

**Comment by antagomir** [comment]
Great work ! If you can add the vignette (the markdown md file that can be generated from the vignette/Rmd file), then it would be easier to comment on the functionality. I made some technical comments in the issues to start with. Let us continue this in the issue tracker of the package.
